source 'http://rubygems.org/'

gem 'sinatra'
gem 'activesupport'
gem 'tux'
gem 'sidekiq'
gem 'foreman'
gem 'thin'
gem 'redis'
gem 'hiredis'
gem 'redis-namespace'

#debugging
gem 'pry'

#AWS
gem 'aws-sdk', '1.29.0'
gem 'aws-sdk-core', git: 'git://github.com/aws/aws-sdk-core-ruby.git'

#messaging
gem 'twilio-ruby', '~> 3.12'
